Update CI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -22,8 +22,18 @@ jobs:
           curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
 
       - name: Build with mdBook
-        run: bin/mdbook build
+        run: bin/mdbook build -v
 
+      - name: Verify `book` Directory Exists
+        run: |
+          if [ -d "book" ]; then 
+            echo "Success: 'book' directory found."; 
+          else 
+            echo "Error: 'book' directory not found!"; 
+            exit 1; 
+          fi
+          echo "Listing all files in the current directory:"
+          ls -R
   deploy:
     needs: build-and-test
     permissions:
